export const statesAndUTs = {
    // States
    AndraPradesh: "Andhra Pradesh",
    ArunachalPradesh: "Arunachal Pradesh",
    Assam: "Assam",
    Bihar: "Bihar",
    Chhattisgarh: "Chhattisgarh",
    Goa: "Goa",
    Gujarat: "Gujarat",
    Haryana: "Haryana",
    HimachalPradesh: "Himachal Pradesh",
    JammuAndKashmir: "Jammu and Kashmir",
    Jharkhand: "Jharkhand",
    Karnataka: "Karnataka",
    Kerala: "Kerala",
    MadhyaPradesh: "Madhya Pradesh",
    Maharashtra: "Maharashtra",
    Manipur: "Manipur",
    Meghalaya: "Meghalaya",
    Mizoram: "Mizoram",
    Nagaland:"Nagaland",
    Odisha: "Odisha",
    Punjab: "Punjab",
    Rajasthan: "Rajasthan",
    Sikkim: "Sikkim",
    TamilNadu: "Tamil Nadu",
    Telangana: "Telangana",
    Tripura: "Tripura",
    UttarPradesh: "Uttar Pradesh",
    Uttarakhand: "Uttarakhand",
    WestBengal: "West Bengal",
  
    // Union Territories
    AndamanAndNicobarIslands: "Andaman and Nicobar Islands",
    Chandigarh: "Chandigarh",
    DadraAndNagarHaveliAndDamanAndDiu: "Dadra and Nagar Haveli and Daman and Diu",
    Delhi: "Delhi",
    Ladakh: "Ladakh",
    Lakshadweep: "Lakshadweep",
    Puducherry: "Puducherry",
  };